app:
  host: 0.0.0.0
  name: Madrid Concert Notifier
  port: 8086
concerts:
  include_unsold_events: true
  target_city: Madrid
  target_country_code: ES
  ticketmaster_api_key: ''
google_calendar:
  alert_time: 09:00
  calendar_id: primary
  enabled: true
  timezone: Europe/Madrid
scanner:
  docker_music_folder: /media
  min_songs_threshold: 3
  music_folder:
  - \\100.95.217.45\omen D\Docker\media-server
  - \\100.95.217.45\omen D\media-library\music-videos
  supported_extensions:
  - .mp3
  - .flac
  - .m4a
  - .ogg
  - .wav
  - .aac
whatsapp:
  enabled: true
  meta_access_token: EAAWWLRYCbxUBSAXlcJ47SWEoIVyu5SXHM9sZCbLZBNYOwRI5AEZAgQvK4NZAYMOThEZCnoZC1VfpGBfybZB22QTKKhApCilmzqZAHhVMIedRWY12uUcJwP0ajujMGCtZAwmZCuUoIpmCZBuX5xqJl1XTNIXqFDCvtGWNIqPu9E3oBmX6uJnnA9MmM2ZAX7t8Nky7Nhxx0AZDZD
  meta_api_version: v20.0
  meta_phone_number_id: '1327474480443417'
  provider: meta
  recipient_number: '34622609030'
